### ISSUE TITLE
React Native Navigation

### ISSUE THREAD

**Issue by dragonfire1119** [hudl/react-native-detox-context#1]
How would this work with React Native Navigation in AppDelegate.m?

**Comment by mrbrentkelly** [comment]
I've never used `react-native-navigation` before (more of a `@react-navigation` fan), but looking at their [docs](https://wix.github.io/react-native-navigation/docs/installing#ios) I would suggest passing the DetoxContext args to the `launchOptions` property in the `AppDelegate`:

```objc
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  [ReactNativeNavigation bootstrapWithDelegate:self launchOptions:[DetoxContext processLaunchArgs]];
  return YES;
}
```
